# Generated by Django 5.0 on 2023-12-28 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squareup', '0004_groupexpense'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupexpense',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
