# Generated by Django 5.0 on 2023-12-28 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('squareup', '0005_groupexpense_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupexpense',
            name='participants',
        ),
    ]
