# Generated by Django 5.0 on 2023-12-28 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squareup', '0006_remove_groupexpense_participants'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupexpense',
            name='payer',
            field=models.TextField(blank=True, null=True),
        ),
    ]
