# Generated by Django 5.0 on 2023-12-29 08:02

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('squareup', '0008_alter_groupexpense_payer'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupexpense',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='groupexpense',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='squareup.group'),
        ),
        migrations.AddField(
            model_name='groupexpense',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
